### ISSUE TITLE
where is the version.h?

### ISSUE THREAD

**Issue by landspace** [qtdevs/auto-version#1]
=.=

**Comment by ericzh86** [comment]
run the python script every time.

**Comment by landspace** [comment]
编译通过。

version.h
=================
#ifndef VERSION_H_88058EC9_4424_4C2A_B52E_17A891AFDEA2
#define VERSION_H_88058EC9_4424_4C2A_B52E_17A891AFDEA2

#define QT_GIT_COMMIT_ID   "077f81a87338e512473ec2c977c821d3d364e323"
#define QT_GIT_AMEND_DATE  "2019-05-16T09:49:16+08:00"
#define QT_GIT_COMMIT_DATE "2019-05-16T09:49:16+08:00"
#define QT_GIT_BUILD_DATE  "2019-06-16T23:25:27+08:00"

#endif//VERSION_H_88058EC9_4424_4C2A_B52E_17A891AFDEA2


环境：
Qt Version  - 5.12.2
Qt Creator Version - 4.6.2
Python Version - 2.7

环境问题：
Qt Creator Version - 4.8.2  会提示 process_begin: CreateProcess(***) failed.

疑问：
1.不知道结果对不对？
2.这个结果和《qmake 版本号自动生成工具》我不理解。
望大佬不吝赐教！
